from __future__ import annotations

import collections

import numpy as np

import pyqtgraph as pg
from acq4.Interfaces import InterfaceMixin
from acq4.util import Qt
from acq4.util.Mutex import Mutex
from acq4.util.geometry import Geometry, load_transform_from_anything
from coorx import Transform, NullTransform, CompositeTransform, SRT3DTransform


def map_through_transform(
    obj: tuple | list | Qt.QPointF | Qt.QVector3D | np.ndarray, tr: Transform
):
    """Map an object through a transform."""
    if not isinstance(tr, Transform):
        raise TypeError(f"Transform must be a coorx Transform, not {type(tr)}")

    # handle special types
    if isinstance(obj, Qt.QPointF):
        return tr.map([obj.x(), obj.y()])
    elif isinstance(obj, Qt.QVector3D):
        return tr.map([obj.x(), obj.y(), obj.z()])
    elif isinstance(obj[0], (Qt.QPointF, Qt.QVector3D)):
        return [map_through_transform(o, tr) for o in obj]

    return tr.map(obj)


class OptomechDevice(InterfaceMixin):
    """
    OptomechDevice is a mixin to the Device class that manages coordinate system mapping between
    rigidly-connected optomechanical devices. For example: movable stages, micromanipulators, changeable
    objective lenses, and imaging/stimulation devices are all considered optomechanical devices.

    These devices are organized hierarchically with each optionally having a parent device and multiple child
    devices. Each device defines its own coordinate transformation that maps from its own local coordinate system
    into its parent's coordinate system.

    This organization makes it simple to map coordinates between devices and the global coordinate system.
    This allows, for example, asking what is the physical location corresponding to a specific pixel in a
    camera image or asking what set of mirror voltages to use in order to stimulate a specific
    physical location.

    In most cases, the transformation will be in the form of an affine matrix multiplication.
    Devices are free, however, to define an arbitrary transformation as well using custom subclasses of
    coorx.Transform.

    Devices may also have a sub-device. For example, a microscope with multiple objectives may
    swap them out as needed. This does not affect the hierarchy of devices, but instead simply
    affects the way the microscope device reports its transformation. Furthermore, it is
    recommended to use information about the currently selected set of subdevices when storing
    and loading device calibration data (for example, a scanner device may store one
    calibration per objective).

    Example device hierarchy:

        <global coordinate system>
                  |
            [Motorized Stage]
                  |
         [Microscope focus drive]
                  |
         [Microscope objectives] ---- subdevice: [ 5x objective ] or [ 63x objective ]
          |       |       |
       [Camera]   |    [Laser] (per-objective power calibration)
                  |
            [Scan Mirrors]
             (per-objective voltage calibration)

    Optomechanical devices may also provide information about their optical filtering characteristics.
    This makes it possible for any device in the system to receive a list of filters that stand between
    itself and the sample. For example:

        <global coordinate system>
                |
            [Microscope]
                |
            [Dichroic]--[Excitation filter]--[Light source]
                |
            [Emission filter]
                |
             [Camera]

    In the example above, images generated by the camera are automatically annotated with information
    about the filters in place between the camera and the sample, as well as the filters in the
    illumination path.
    """

    # these signals are proxied from the OptomechDevice object
    # we do this to avoid QObject double-inheritance issues.
    class SignalProxyObject(Qt.QObject):
        # emitted when this device's transform changes
        sigTransformChanged = Qt.Signal(object)  # self
        # emitted when the transform for this device or any of its parents changes
        sigGlobalTransformChanged = Qt.Signal(object, object)  # self, changed device

        # Emitted when this device's optics change
        sigOpticsChanged = Qt.Signal(object, object)  # self, port
        # Emitted when the optics for this device or any of its parents changes
        sigGlobalOpticsChanged = Qt.Signal(object, object, object)  # self, changed device, port

        # Emitted when this device changes its current subdevice
        sigSubdeviceChanged = Qt.Signal(object, object, object)  # self, new subdev, old subdev
        # Emitted when this device or any (grand)parent changes its current subdevice
        sigGlobalSubdeviceChanged = Qt.Signal(
            object, object, object, object
        )  # self, dev, new subdev, old subdev

        sigGeometryChanged = Qt.Signal(object)  # self

    def __init__(self, dm, config, name):
        object.__init__(self)

        # create proxy object and wrap in its signals
        self.__sigProxy = OptomechDevice.SignalProxyObject()
        self.sigTransformChanged = self.__sigProxy.sigTransformChanged
        self.sigGlobalTransformChanged = self.__sigProxy.sigGlobalTransformChanged
        self.sigOpticsChanged = self.__sigProxy.sigOpticsChanged
        self.sigGlobalOpticsChanged = self.__sigProxy.sigGlobalOpticsChanged
        self.sigSubdeviceChanged = self.__sigProxy.sigSubdeviceChanged
        self.sigGlobalSubdeviceChanged = self.__sigProxy.sigGlobalSubdeviceChanged
        self.sigGeometryChanged = self.__sigProxy.sigGeometryChanged

        # Redundant: Device also saves these
        self.__devManager = dm
        self.__config = config
        self.__name = name

        # __ports is a list of port names to which devices may be attached.
        # Most devices will have a single port called 'default' to which all children attach.
        # In some cases, the device has a specific set of named ports where children
        # can be attached (eg: a dichroic filter cube might have "excitation" and "emission" ports).
        self.__ports = []

        # All devices have 0 or 1 parent
        self.__parent = None
        # When connected to a parent device, we also optionally specify *where* on
        # the device to connect (usually this is just 'default').
        self.__parentPort = None

        # Contains {port: [list of optics]} describing the optics (usually filters) for each port
        self.__optics = {}

        # Swappable sub-devices. (eg: objective changers, filter wheels)
        self.__subdevice = None

        self.__lock = Mutex(recursive=True, debug=False)

        self.sigTransformChanged.connect(
            self.__emitGlobalTransformChanged, type=Qt.Qt.DirectConnection
        )
        self.sigOpticsChanged.connect(self.__emitGlobalOpticsChanged, type=Qt.Qt.DirectConnection)
        self.sigSubdeviceChanged.connect(
            self.__emitGlobalSubdeviceChanged, type=Qt.Qt.DirectConnection
        )

        if config is None:
            config = {}
        self.__ports = config.get("ports", ["default"])
        assert isinstance(self.__ports, list)
        self.__optics = config.get("optics", {"default": []})
        assert isinstance(self.__optics, dict)

        if "transform" in config:
            self.__transform = load_transform_from_anything(config["transform"])
        else:
            self.__transform = SRT3DTransform(dims=(3, 3))

        # This transform maps from the device's local coordinate system to the parent device's coordinate system
        self._deviceTransformWrapper = CompositeTransform(self.__transform, NullTransform(dims=(3, 3)))
        self.deviceTransform.add_change_callback(self._handleDeviceTransformChange)

        self.physicalTransform = CompositeTransform(self._physicalTransform, NullTransform(dims=(3, 3)))

        # This transform maps from local device coordinates to global coordinates
        self.globalTransform = CompositeTransform(NullTransform(dims=(3, 3)), self.deviceTransform)
        self.globalPhysicalTransform = CompositeTransform(
            NullTransform(dims=(3, 3)), self.physicalTransform
        )

        if "parentDevice" in config:
            try:
                parent = config["parentDevice"]
                if isinstance(parent, str):
                    self.setParentDevice(parent)
                elif isinstance(parent, dict) and "name" in parent:
                    self.setParentDevice(parent["name"], port=parent.get("port", "default"))
                else:
                    raise TypeError(f"Invalid parent device specification: {parent!r}")

            except Exception as ex:
                if "No device named" not in ex.args[0]:
                    raise
                print(
                    f"Cannot set parent device {config['parentDevice']!r}; no device by that name."
                )
                print("Available devices:", dm.listDevices())

        # declare that this device supports the OptomechDevice API
        self.addInterface("OptomechDevice")
        dm.declareInterface(name, ["OptomechDevice"], self)

    @property
    def deviceTransform(self):
        return self._deviceTransformWrapper

    @deviceTransform.setter
    def deviceTransform(self, tr):
        """This sets the fundamental transform for this device, which is notably different from the
        return of `self.deviceTransform` due to the need to use the coorx change events."""
        self.__transform = tr
        self.deviceTransform.transforms = [tr, self.deviceTransform.transforms[1]]

    def _handleDeviceTransformChange(self, change):
        self.sigTransformChanged.emit(self)

    def getGeometry(self, name=None) -> Geometry | None:
        if "geometry" in self.__config:
            name = self.geometryCacheKey if name is None else name
            return Geometry(
                config=self.__config["geometry"],
                name=f"[primary geometry of {name}]",
                parent_name=name,
            )
        return None

    @property
    def geometryCacheKey(self) -> str:
        key = self.getDeviceStateKey()
        if key:
            return str(key)
        return self.name()

    def getBoundaries(self):
        return []

    def name(self):
        return self.__name

    def ports(self):
        """Return a list of the names of ports to which children may be attached."""
        return self.__ports[:]

    def parentDevice(self) -> "OptomechDevice | None":
        """Return this device's parent, or None if there is no parent."""
        return self.__parent

    def parentPort(self):
        """Return the port on this device's parent to which this device is attached."""
        return self.__parentPort

    @property
    def _physicalTransform(self):
        """Return the transform mapping from this device's local coordinate system to its parent's
        physical coordinate system. By default, this is the same as deviceTransform, but subclasses
        may override this to provide a mapping that excludes optical effects.
        """
        return self.deviceTransform

    @property
    def deviceOffset(self):
        return self.__transform.offset

    @deviceOffset.setter
    def deviceOffset(self, offset):
        self.__transform.offset = offset

    @property
    def deviceScale(self):
        return self.__transform.scale

    @deviceScale.setter
    def deviceScale(self, scale):
        self.__transform.scale = scale

    @property
    def deviceRotation(self):
        return self.__transform.rotation

    def setParentDevice(self, parent: "str | OptomechDevice", port="default"):
        """Set the parent of this device.

        If *parent* is None, then the device has no parent and its transform is assumed to
        be relative to the global coordinate system.

        If *port* is specified, then the device is attached to a named port on the
        parent device.
        """
        with self.__lock:
            # disconnect from previous parent if needed
            if self.__parent is not None:
                self.__parent.sigGlobalTransformChanged.disconnect(
                    self.__parentDeviceTransformChanged
                )
                self.__parent.sigGlobalOpticsChanged.disconnect(self.__parentOpticsChanged)
                self.__parent.sigGlobalSubdeviceChanged.disconnect(self.__parentSubdeviceChanged)

            # look up device from its name
            if isinstance(parent, str):
                parent = self.__devManager.getDevice(parent)

            # connect to the new parent
            self.__parent = None
            self.__parentPort = None
            if parent is None:
                # setting transforms handles old/new callback connections
                self.globalTransform.transforms = [NullTransform(dims=(3, 3)), self.deviceTransform]
                self.globalPhysicalTransform.transforms = [
                    NullTransform(dims=(3, 3)),
                    self.physicalTransform,
                ]
                return

            self.globalTransform.transforms = [parent.deviceTransform, self.deviceTransform]
            self.globalPhysicalTransform.transforms = [
                parent.physicalTransform,
                self.physicalTransform,
            ]

            if port not in parent.ports():
                raise ValueError(
                    f"Cannot connect to port {port!r} on device {parent!r}; available ports are: {parent.ports()!r}"
                )

            parent.sigGlobalTransformChanged.connect(
                self.__parentDeviceTransformChanged, type=Qt.Qt.DirectConnection
            )
            parent.sigGlobalOpticsChanged.connect(
                self.__parentOpticsChanged, type=Qt.Qt.DirectConnection
            )
            parent.sigGlobalSubdeviceChanged.connect(
                self.__parentSubdeviceChanged, type=Qt.Qt.DirectConnection
            )
            self.__parent = parent
            self.__parentPort = port

    def mapToParentDevice(self, obj):
        """Map from local coordinates to the parent device (or to global if there is no parent)"""
        return map_through_transform(obj, self.deviceTransform)

    def mapToGlobal(self, obj):
        """Map *obj* from local coordinates to global."""
        return map_through_transform(obj, self.globalTransform)

    def mapToDevice(self, device, obj):
        """Map *obj* from local coordinates to *device*'s coordinate system."""
        return device.mapFromGlobal(self.mapToGlobal(obj))

    def mapFromParentDevice(self, obj):
        """Map *obj* from parent coordinates (or from global if there is no parent) to local coordinates."""
        return map_through_transform(obj, self.deviceTransform.inverse)

    def mapFromGlobal(self, obj):
        """Map *obj* from global to local coordinates."""
        return map_through_transform(obj, self.globalTransform.inverse)

    def mapGlobalToParent(self, obj):
        """Map *obj* from global coordinates to the parent device coordinates.
        If this device has no parent, then *obj* is returned unchanged.
        """
        if self.parentDevice() is None:
            return obj
        else:
            return self.parentDevice().mapFromGlobal(obj)

    def mapParentToGlobal(self, obj):
        """Map *obj* from parent device coordinates to global coordinates.
        If this device has no parent, then *obj* is returned unchanged.
        """
        if self.parentDevice() is None:
            return obj
        else:
            return self.parentDevice().mapToGlobal(obj)

    def listOptics(self, port="default"):
        """Return a list of Optics this device adds to the optical
        path from its children to its parent, in physical order.

        If *port* is given, then optics are listed for the specified
        attachment port (eg: 'excitation' or 'emission' for dichroic devices).
        """
        optics = self.__optics.get(port, [])[:]

        # Add in optics from current subdevice. This allows swappable filter configurations.
        dev = self.subdevice
        if dev is not None:
            optics = optics + dev.listOptics(port)
        return optics

    def setOptics(self, optics, port="default"):
        """Set this device's list of optics for the specified port."""
        self.__optics[port] = optics
        self.sigOpticsChanged.emit(self, port)

    def listGlobalOptics(self):
        """Return a list of all optics in the path from this device to the sample."""
        optics = []
        dev = self
        while True:
            parent = dev.parentDevice()
            if parent is None:
                break
            parentPort = dev.parentPort()
            optics += parent.listOptics(parentPort)
            dev = parent

        return optics

    def __emitGlobalTransformChanged(self):
        self.sigGlobalTransformChanged.emit(self, self)

    def __emitOpticsChanged(self, port):
        self.sigOpticsChanged.emit(self, port)

    def __emitGlobalOpticsChanged(self, sender, port):
        self.sigGlobalOpticsChanged.emit(self, sender, port)

    def __emitGlobalSubdeviceChanged(self, sender, newDev, oldDev):
        self.sigGlobalSubdeviceChanged.emit(self, sender, newDev, oldDev)

    def __parentDeviceTransformChanged(self, sender, changed):
        # called when any (grand)parent's transform has changed.
        self.sigGlobalTransformChanged.emit(self, changed)

    def __parentOpticsChanged(self, sender, device, port):
        # called when any (grand)parent's optics have changed
        self.sigGlobalOpticsChanged.emit(self, device, port)

    def __parentSubdeviceChanged(self, sender, parent, newDev, oldDev):
        # called when any (grand)parent's current subdevice has changed.
        self.sigGlobalSubdeviceChanged.emit(self, parent, newDev, oldDev)

    def ancestorDevices(self):
        """
        Return a list of this device and its parent devices in hierarchical order:
        [self, parent, grandparent, ...]
        """
        parents = [self]
        p = self
        while True:
            p = p.parentDevice()
            if p is None:
                break
            parents.append(p)
        return parents

    @property
    def subdevice(self):
        """Return the currently selected subdevice, or None if there is no subdevice selected."""
        return self.__subdevice

    @subdevice.setter
    def subdevice(self, dev):
        with self.__lock:
            oldDev = self.__subdevice
            if oldDev is not None:
                oldDev.sigOpticsChanged.disconnect(self.__emitOpticsChanged)
            self.__subdevice = dev
            if dev is None:
                self.deviceTransform.transforms = [self.__transform, NullTransform(dims=(3, 3))]
                self.physicalTransform.transforms = [self._physicalTransform, NullTransform(dims=(3, 3))]
            else:
                self.deviceTransform.transforms = [self.__transform, dev.deviceTransform]
                self.physicalTransform.transforms = [self._physicalTransform, dev.physicalTransform]
                dev.sigOpticsChanged.connect(
                    self.__emitOpticsChanged, type=Qt.Qt.DirectConnection
                )
        self.sigSubdeviceChanged.emit(self, dev, oldDev)

    def deviceTransformWithHypotheticalSubdevice(self, dev):
        """Return the deviceTransform that would be in effect if the specified subdevice were selected."""
        if dev is None:
            return CompositeTransform(self.__transform, NullTransform(dims=(3, 3)))
        else:
            return CompositeTransform(self.__transform, dev.deviceTransform)

    def treeSubdeviceState(self):
        """return an ordered dict of {devName: subdevName} pairs indicating the currently
        selected subdevices throughout the tree."""
        devices = [self] + self.ancestorDevices()
        subdevs = collections.OrderedDict()
        for dev in devices:
            if dev.subdevice is not None:
                subdevs[dev.name()] = dev.subdevice.name()
        return subdevs

    def getDeviceStateKey(self) -> tuple[str, ...]:
        """
        Return a tuple that uniquely identifies the state of all subdevice selections in the system.
        This may be used as a key for storing/retrieving calibration data.
        """
        state = self.treeSubdeviceState()
        devs = sorted(state.keys())
        return tuple(f"{dev}__{state[dev]}" for dev in devs)

    def getFocusDepth(self):
        """Return the Z position of this device's origin, mapped to the global coordinate system."""
        return self.mapToGlobal([0, 0, 0])[2]

    def setFocusDepth(self, depth, speed="slow"):
        """Set microscope focus such that this device's origin is moved to the specified global Z position."""
        dev = self.getFocusDevice()
        if dev is None:
            raise ValueError(f"Device {dev} is not connected to a focus controller.")
        dz = depth - self.getFocusDepth()
        dpos = dev.globalPosition()
        return dev.moveToGlobal([dpos[0], dpos[1], dpos[2] + dz], speed)

    def getFocusDevice(self):
        """Return the device that provides focus capabilities for this device."""
        dev = self.parentDevice()
        from .Stage import Stage

        while dev is not None:
            if isinstance(dev, Stage) and dev.capabilities()["setPos"][2]:
                return dev
            dev = dev.parentDevice()
        return None
